version: '3'
services:
  scheduler:
    image: daskdev/dask:latest
    command: ["dask-scheduler"]
    ports:
      - "8786:8786"

  worker:
    image: daskdev/dask:latest
    command: ["dask-worker", "scheduler:8786"]
    depends_on:
      - scheduler